# Generated by Django 3.0.8 on 2020-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(blank=True, max_length=255, null=True)),
                ('your_phone', models.IntegerField(blank=True, null=True)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_address', models.CharField(blank=True, max_length=255, null=True)),
                ('your_scheldule', models.CharField(blank=True, max_length=255, null=True)),
                ('your_time', models.CharField(blank=True, max_length=255, null=True)),
                ('your_message', models.TextField()),
            ],
        ),
    ]
